### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by xixilidehuoshan** [Tramac/awesome-semantic-segmentation-pytorch#106]
(pytorch) G:\awesome-semantic-segmentation-pytorch-master\core\nn>python setup.py build develop
running build
running build_ext
F:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building '._C' extension
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    cmdclass={"build_ext": BuildExtension}
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "F:\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\pytorch\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 343, in build_extensions
    build_ext.build_extensions(self)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "F:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 333, in win_wrap_compile
    extra_postargs, depends)
  File "F:\Anaconda3\envs\pytorch\lib\distutils\_msvccompiler.py", line 345, in compile
    self.initialize()
  File "F:\Anaconda3\envs\pytorch\lib\distutils\_msvccompiler.py", line 238, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
    return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
  File "F:\Anaconda3\envs\pytorch\lib\site-packages\setuptools\msvc.py", line 1620, in return_env
    if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
  File "F:\Anaconda3\envs\pytorch\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

CUDA 10  torch1.0.0

**Comment by xixilidehuoshan** [comment]
Is it an environmental question？
