### ISSUE TITLE
core/nn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

### ISSUE THREAD

**Issue by Hussainflr** [Tramac/awesome-semantic-segmentation-pytorch#108]
Hi there,
I'm getting this error "undefined symbol: _ZN3c1011CPUTensorIdEv". Although I have followed setup instructions correctly, and it installs everything without any error or warning. But when I'm trying to run the fcn32 training script it gives this error. Any help or suggestion would be highly appreciated. Below is the error traceback.   

Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from core.data.dataloader import get_segmentation_dataset
  File "segmentation/awesome-semantic-segmentation-pytorch/core/__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "segmentation/awesome-semantic-segmentation-pytorch/core/nn/__init__.py", line 4, in <module>
    from .ca_block import *
  File "segmentation/awesome-semantic-segmentation-pytorch/core/nn/ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: segmentation/awesome-semantic-segmentation-pytorch/core/nn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

**Comment by qingzi02010** [comment]
@Hussainflr I encountered the same problem, and the env is also same with yours. Did you solve it? Thank you!

**Comment by guo49** [comment]
> @Hussainflr I encountered the same problem, and the env is also same with yours. Did you solve it? Thank you!

I also encountered this problem, and then I solved it by deleting the build folder. Hope it can help you.
