### ISSUE TITLE
undefined symbol: _Z23LeakyRelu_Backward_CUDAN2at6TensorES0_f

### ISSUE THREAD

**Issue by kernel-Peanut** [Tramac/awesome-semantic-segmentation-pytorch#11]
it occurs this error when I run train.py 

Traceback (most recent call last):
  File "scripts/train.py", line 17, in <module>
    from core.data.dataloader import get_segmentation_dataset
  File "/mnt/v-yuxzho/code/awesome-semantic-segmentation-pytorch-master/core/__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "/mnt/v-yuxzho/code/awesome-semantic-segmentation-pytorch-master/core/nn/__init__.py", line 2, in <module>
    from .sync_bn.syncbn import *
  File "/mnt/v-yuxzho/code/awesome-semantic-segmentation-pytorch-master/core/nn/sync_bn/syncbn.py", line 17, in <module>
    from .functions import *
  File "/mnt/v-yuxzho/code/awesome-semantic-segmentation-pytorch-master/core/nn/sync_bn/functions.py", line 15, in <module>
    from core.nn.sync_bn import lib
  File "/mnt/v-yuxzho/code/awesome-semantic-segmentation-pytorch-master/core/nn/sync_bn/lib/__init__.py", line 19, in <module>
    build_directory=gpu_path, verbose=False)
  File "/mnt/yueshangGu/Apps/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/mnt/yueshangGu/Apps/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/mnt/yueshangGu/Apps/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 968, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/mnt/yueshangGu/Apps/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/mnt/yueshangGu/Apps/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /mnt/v-yuxzho/code/awesome-semantic-segmentation-pytorch-master/core/nn/sync_bn/lib/gpu/sync_gpu.so: undefined symbol: _Z23LeakyRelu_Backward_CUDAN2at6TensorES0_f

**Comment by kernel-Peanut** [comment]
I follow this issue https://github.com/zhanghang1989/PyTorch-Encoding/issues/127#issue-364292560 and upgrade the torch-encoding ,but it doesn't work

**Comment by dekura** [comment]
> I follow this issue [zhanghang1989/PyTorch-Encoding#127 (comment)](https://github.com/zhanghang1989/PyTorch-Encoding/issues/127#issue-364292560) and upgrade the torch-encoding ,but it doesn't work

@kernel-Peanut i meet this problem too. Have you find how to solve it? Thank you so much.

**Comment by dekura** [comment]
Hi, @kernel-Peanut @Tramac 
I solved this problem by changing the files in /core/nn/sync_bn/lib/gpu

### first
change the syncbn_kernel.cu as follow

before
```cpp
#include <vector>
#include <torch/extension.h>
#include <ATen/ATen.h>
#include <ATen/cuda/CUDAContext.h>
```
after
```cpp
#include <vector>
#include <torch/serialize/tensor.h>
#include <ATen/ATen.h>
#include <ATen/cuda/CUDAContext.h>
```

### second
and do follow the issue [here](https://github.com/zhanghang1989/PyTorch-Encoding/issues/140#issuecomment-443141984)

**Comment by Tramac** [comment]
Good job, thank you very much!

**Comment by kernel-Peanut** [comment]
@dekura  It doesn't work for me .
I change #include <torch/extension.h>  to #include <torch/serialize/tensor.h>  and rename the torch/torch.h to torch/extension.h , but it doesn't work.

**Comment by dekura** [comment]
@kernel-Peanut you con refer to [my code here](https://github.com/dekura/awesome-semantic-segmentation-pytorch/tree/master/core/nn/sync_bn/lib/gpu) and see which torch.h should be changed and which should not.
or you can just change the core/nn/sync_bn/lib/gpu folder with mine~
Have a try~

**Comment by dekura** [comment]
@kernel-Peanut  i tried again and i found that you must delete all the codes about `LeakyRelu_Backward` and `LeakyRelu_Forward` in  core/nn/sync_bn/lib/gpu

**Comment by kernel-Peanut** [comment]
@dekura 
Hey! The bug disappear after following your method. Thanks a lot!

**Comment by kernel-Peanut** [comment]
@Tramac 
I think this issue can be closed.

**Comment by Tramac** [comment]
@kernel-Peanut @dekura 
Hi, the bug `undefined symbol: _Z23LeakyRelu_Backward_CUDAN2at6TensorES0_f ` in syncbn has been fixed with no remove leakyrelu.
Thank you for your job!
