### ISSUE TITLE
KeyError: 'local_rank'

### ISSUE THREAD

**Issue by srcn9595** [Tramac/awesome-semantic-segmentation-pytorch#110]
Hi,
"`python3 demo.py --model fcn32s_vgg16_voc --input-pic ./datasets/test.png`" running.

Error Code:
```
Traceback (most recent call last):
  File "demo.py", line 58, in <module>
    demo(args)
  File "demo.py", line 44, in demo
    model = get_model(args.model, pretrained=True, root=args.save_folder).to(device)
  File "/home/sercan/awesome-semantic-segmentation-pytorch/core/models/model_zoo.py", line 90, in get_model
    net = _models[name](**kwargs)
  File "/home/sercan/awesome-semantic-segmentation-pytorch/core/models/fcn.py", line 209, in get_fcn32s_vgg16_voc
    return get_fcn32s('pascal_voc', 'vgg16', **kwargs)
  File "/home/sercan/awesome-semantic-segmentation-pytorch/core/models/fcn.py", line 164, in get_fcn32s
    device = torch.device(kwargs['local_rank'])
KeyError: 'local_rank'
```
Why am I getting such an error? Can you help me ?

**Comment by YLONl** [comment]
i got the same error.did you solve the problem

**Comment by miaodd98** [comment]
I have the same issue when I was trying to evaluate the fcn model with resnet50 backbone. Weird thing is that 'local_rank' is not an argument for running, but when trying to load the model it just appears. Hoping to solve this issue.

**Comment by miaodd98** [comment]
Debugging the program seems not find any runtime errors, so weird.

**Comment by miaodd98** [comment]
It seems that this error would happen on resnet backbone, weird thing that there is a value at local_rank parameter which points out the current GPU device. Still don't know why this error happens.

**Comment by YLONl** [comment]
i get this error because of running demo.py  . I run train.py without this error.

**Comment by miaodd98** [comment]
There is no problem when training. I found this issue when running eval.py .

**Comment by renmmmmmm** [comment]
Found 1449 images in the folder /home/all/datasets/VOC/VOCdevkit/VOC2012
Traceback (most recent call last):
  File "eval.py", line 116, in <module>
    evaluator = Evaluator(args)
  File "eval.py", line 51, in __init__
    norm_layer=BatchNorm2d).to(self.device)#args.local_rank,
  File "/home/renshasha/awesome-semantic-segmentation-pytorch-master/core/models/model_zoo.py", line 124, in get_segmentation_model
    return models[model](**kwargs)
  File "/home/renshasha/awesome-semantic-segmentation-pytorch-master/core/models/pspnet.py", line 132, in get_psp
    model = PSPNet(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
  File "/home/renshasha/awesome-semantic-segmentation-pytorch-master/core/models/pspnet.py", line 35, in __init__
    super(PSPNet, self).__init__(nclass, aux, backbone, pretrained_base=pretrained_base, **kwargs)
  File "/home/renshasha/awesome-semantic-segmentation-pytorch-master/core/models/segbase.py", line 26, in __init__
    self.pretrained = resnet50_v1s(pretrained=pretrained_base, dilated=dilated, **kwargs)
  File "/home/renshasha/awesome-semantic-segmentation-pytorch-master/core/models/base_models/resnetv1b.py", line 236, in resnet50_v1s
    model = ResNetV1b(BottleneckV1b, [3, 4, 6, 3], deep_stem=True, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'local_rank'

**Comment by renmmmmmm** [comment]
Found 1449 images in the folder /home/all/datasets/VOC/VOCdevkit/VOC2012
Traceback (most recent call last):
  File "eval.py", line 116, in <module>
    evaluator = Evaluator(args)
  File "eval.py", line 51, in __init__
    norm_layer=BatchNorm2d).to(self.device)#args.local_rank,
  File "/home//awesome-semantic-segmentation-pytorch-master/core/models/model_zoo.py", line 124, in get_segmentation_model
    return models[model](**kwargs)
  File "/home//awesome-semantic-segmentation-pytorch-master/core/models/pspnet.py", line 132, in get_psp
    model = PSPNet(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
  File "/home//awesome-semantic-segmentation-pytorch-master/core/models/pspnet.py", line 35, in __init__
    super(PSPNet, self).__init__(nclass, aux, backbone, pretrained_base=pretrained_base, **kwargs)
  File "/home//awesome-semantic-segmentation-pytorch-master/core/models/segbase.py", line 26, in __init__
    self.pretrained = resnet50_v1s(pretrained=pretrained_base, dilated=dilated, **kwargs)
  File "/home//awesome-semantic-segmentation-pytorch-master/core/models/base_models/resnetv1b.py", line 236, in resnet50_v1s
    model = ResNetV1b(BottleneckV1b, [3, 4, 6, 3], deep_stem=True, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'local_rank'

**Comment by sainatarajan** [comment]
Instead of kwargs['local_rank'] in eval.py or demo.py, substitute it with 0 or 1 accordingly whether its cpu or cuda. So, that specific line becomes device= torch.device(0) or device= torch.device(1). Please close this issue if this works for you. It had worked for me.

**Comment by xyry** [comment]
I got the same error, then I modify the file like this, it works. I hope this will help you.
https://github.com/xyry/awesome-semantic-segmentation-pytorch/pull/1/commits/05b7de785dd15e618ce82418619a358bf472ca01

**Comment by morememes** [comment]
Same error in demo.py, I modified demo.py like this.

`model = get_model(args.model, pretrained=True, root=args.save_folder, local_rank=device).to(device)`
It works for me.

**Comment by Yvette1993** [comment]
> Instead of `kwargs['local_rank']` in `eval.py` or `demo.py`, substitute it with 0 or 1 accordingly whether its cpu or cuda. So, that specific line becomes `device= torch.device(0)` or `device= torch.device(1)`. Please close this issue if this works for you. It had worked for me.

Excuse me. When I set "local_rank = 0", It's to say only using GPU 0, but I get the ERROR like this:
RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 7.79 GiB total capacity; 4.74 GiB already allocated; 1.72 GiB free; 4.87 GiB reserved in total by PyTorch). So what  I can do if I want to using two gpus? Thanks.

**Comment by yyywxk** [comment]
I also got the same error, then I modify the `core/models/base_models/resnetv1b.py` in line 95 like this:
`zero_init_residual=False, norm_layer=nn.BatchNorm2d, **kwargs):`

**Comment by Yvette1993** [comment]
> I also got the same error, then I modify the `core/models/base_models/resnetv1b.py` in line 95 like this:
> `zero_init_residual=False, norm_layer=nn.BatchNorm2d, **kwargs):`

Excuse me. When I change it like you said, but I got same error. Do you change any code in eval.py or train.py file? or what's your eval command

**Comment by yyywxk** [comment]
> > I also got the same error, then I modify the `core/models/base_models/resnetv1b.py` in line 95 like this:
> > `zero_init_residual=False, norm_layer=nn.BatchNorm2d, **kwargs):`
> 
> Excuse me. When I change it like you said, but I got same error. Do you change any code in eval.py or train.py file? or what's your eval command

The error of `CUDA out of memory` is not related to this change. It means that the GPU memory is not enough to deal with your images. Multi-GPU evaluating maybe help, or crop the image into a small size.

**Comment by Yvette1993** [comment]
> > > I also got the same error, then I modify the `core/models/base_models/resnetv1b.py` in line 95 like this:
> > > `zero_init_residual=False, norm_layer=nn.BatchNorm2d, **kwargs):`
> > 
> > 
> > Excuse me. When I change it like you said, but I got same error. Do you change any code in eval.py or train.py file? or what's your eval command
> 
> The error of `CUDA out of memory` is not related to this change. It means that the GPU memory is not enough to deal with your images. Multi-GPU evaluating maybe help, or crop the image into a small size.

I using Multi-GPU evaluating command like this:
export NGPUS=2
python -m torch.distributed.launch --nproc_per_node=$NGPUS eval.py --model danet --backbone resnet50 --dataset citys --resume ./torch/models/danet_resnet50_citys_best_model.pth --batch-size 1
but meet same error, because it's only using gpus-1 actually. so I ask you whether changed other code, that can using two gpu simultaneously. Thanks.

**Comment by chang0424** [comment]
@morememes ,it works for me,too.thank you very much!

**Comment by liuqinglong110** [comment]
> I got the same error, then I modify the file like this, it works. I hope this will help you.
> [xyry@05b7de7](https://github.com/xyry/awesome-semantic-segmentation-pytorch/commit/05b7de785dd15e618ce82418619a358bf472ca01)

Thanks,  it works!

**Comment by dawang-11** [comment]
> I got the same error, then I modify the file like this, it works. I hope this will help you. [xyry@05b7de7](https://github.com/xyry/awesome-semantic-segmentation-pytorch/commit/05b7de785dd15e618ce82418619a358bf472ca01)

Traceback (most recent call last):
  File "eval.py", line 113, in <module>
    evaluator.eval()
  File "eval.py", line 59, in eval
    self.metric.reset()
AttributeError: 'Evaluator' object has no attribute 'metric'
