### ISSUE TITLE
TypeError: forward() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by dekura** [Tramac/awesome-semantic-segmentation-pytorch#12]
Hi, @Tramac :
I use command as follow:
```shell
CUDA_VISIBLE_DEVICES=4,5,6,7 python train.py --model psp --backbone resnet50 --dataset coco
```
then  i got error

```shell
loading annotations into memory...
Done (t=2.22s)
creating index...
index created!
Starting Epoch: 0, Total Epochs: 60
Traceback (most recent call last):
  File "train.py", line 248, in <module>
    trainer.train()
  File "train.py", line 183, in train
    loss = self.criterion(outputs, targets)
  File "/home/luqi/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/utils/parallel.py", line 81, in forward
    outputs = criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/utils/parallel.py", line 163, in criterion_parallel_apply
    raise output
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/utils/parallel.py", line 139, in _worker
    output = module(*(list(input) + [target]), **kwargs)
  File "/home/luqi/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/nn/loss.py", line 32, in forward
    return super(MixSoftmaxCrossEntropyLoss, self).forward(*inputs)
TypeError: forward() takes 3 positional arguments but 4 were given
```

I dont quite understand what it means. Can you help me?

**Comment by Tramac** [comment]
Hi, I can't see the bug information, can you repost it?

**Comment by dekura** [comment]
Sorry my network failed last moment. And i have reposted it~

**Comment by Tramac** [comment]
Please print size of inputs before `return super(MixSoftmaxCrossEntropyLoss, self).forward(*inputs)`:
```
for i in range(len(inputs)):
    print(inputs[i].size())
```

**Comment by dekura** [comment]
it shows 

```shell
creating index...
index created!
Starting Epoch: 0, Total Epochs: 60
torch.Size([21, 480, 480])
torch.Size([21, 480, 480])
torch.Size([21, 480, 480])
torch.Size([21, 480, 480])
torch.Size([21, 480, 480])
torch.Size([21, 480, 480])
torch.Size([21, 480, 480])
torch.Size([21, 480, 480])
Traceback (most recent call last):
  File "train.py", line 248, in <module>
    trainer.train()
  File "train.py", line 183, in train
    loss = self.criterion(outputs, targets)
  File "/home/luqi/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/utils/parallel.py", line 81, in forward
    outputs = criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/utils/parallel.py", line 163, in criterion_parallel_apply
    raise output
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/utils/parallel.py", line 139, in _worker
    output = module(*(list(input) + [target]), **kwargs)
  File "/home/luqi/anaconda3/envs/pytorch-1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/luqi/guojin/codes/awesome-semantic-segmentation-pytorch/core/nn/loss.py", line 33, in forward
    print(inputs[i].size())
AttributeError: 'tuple' object has no attribute 'size'
```

**Comment by dekura** [comment]
And before i run this code, i did as you told [here](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/issues/10#issuecomment-486627694) in this issue #10 .
i changed `output = module(*(list(input) + target), **kwargs)` to`output = module(*(list(input) + [target]), **kwargs)`

**Comment by Tramac** [comment]
Please try to remove [code](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/28275b46f711d1ddf7b2df371e73085f588630be/core/nn/loss.py#L27-28):
```
preds, target = tuple(inputs)
inputs = tuple(list(preds) + [target])
```

**Comment by zhiyuli3** [comment]
> And before i run this code, i did as you told [here](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/issues/10#issuecomment-486627694) in this issue #10 .
> i changed `output = module(*(list(input) + target), **kwargs)` to`output = module(*(list(input) + [target]), **kwargs)`

Hi ? Do you solve this problem?

**Comment by Tramac** [comment]
Hi, I'm very sorry that there is not enough devices to debug `parallel.py` now. I have add distributed training, which is faster than `parallel.py`, please try it.
When I fix the bug in `parallel.py`, i will tell you.

**Comment by dekura** [comment]
Thank you~ i will try
