### ISSUE TITLE
run demo.py  KeyError: 'voc'

### ISSUE THREAD

**Issue by lph529372693** [Tramac/awesome-semantic-segmentation-pytorch#140]
Hi 

I've trained the bisenet_resnet18_voc model，and I've add code in bisenet.py&model_zoo.py.But I run demo.py(python3 demo.py --model bisenet_resnet18_voc --input-pic ./datasets/2007_000032.jpg),the error occurred as follows：

Traceback (most recent call last):
  File "demo.py", line 58, in <module>
    demo(args)
  File "demo.py", line 44, in demo
    model = get_model(args.model, pretrained=True, root=args.save_folder).to(device)
  File "/home/leo/PycharmProjects/semseg/awesome-semantic-segmentation-pytorch-master/core/models/model_zoo.py", line 91, in get_model
    net = _models[name](**kwargs)
  File "/home/leo/PycharmProjects/semseg/awesome-semantic-segmentation-pytorch-master/core/models/bisenet.py", line 215, in get_bisenet_resnet18_voc
    return get_bisenet('voc', 'resnet18', **kwargs)
  File "/home/leo/PycharmProjects/semseg/awesome-semantic-segmentation-pytorch-master/core/models/bisenet.py", line 204, in get_bisenet
    model = BiSeNet(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
KeyError: 'voc'

How to solve it？
Thanks！！！

**Comment by lph529372693** [comment]
> Hi
> 
> I've trained the bisenet_resnet18_voc model，and I've add code in bisenet.py&model_zoo.py.But I run demo.py(python3 demo.py --model bisenet_resnet18_voc --input-pic ./datasets/2007_000032.jpg),the error occurred as follows：
> 
> Traceback (most recent call last):
> File "demo.py", line 58, in
> demo(args)
> File "demo.py", line 44, in demo
> model = get_model(args.model, pretrained=True, root=args.save_folder).to(device)
> File "/home/leo/PycharmProjects/semseg/awesome-semantic-segmentation-pytorch-master/core/models/model_zoo.py", line 91, in get_model
> net = _models[name](**kwargs)
> File "/home/leo/PycharmProjects/semseg/awesome-semantic-segmentation-pytorch-master/core/models/bisenet.py", line 215, in get_bisenet_resnet18_voc
> return get_bisenet('voc', 'resnet18', **kwargs)
> File "/home/leo/PycharmProjects/semseg/awesome-semantic-segmentation-pytorch-master/core/models/bisenet.py", line 204, in get_bisenet
> model = BiSeNet(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
> KeyError: 'voc'
> 
> How to solve it？
> Thanks！！！
