### ISSUE TITLE
Error: failed to send plot to http://127.0.0.1:63342

### ISSUE THREAD

**Issue by LiZhangMing** [Tramac/awesome-semantic-segmentation-pytorch#148]
I run the evel.py, I used the pycharm 2020 and i got a error:

Error: failed to send plot to http://127.0.0.1:63342
Traceback (most recent call last):
  File "/home/nihao/.pycharm_helpers/pycharm_display/datalore/display/display_.py", line 60, in _send_display_message
    urlopen(url, buffer)
  File "/home/nihao/miniconda2/envs/py36/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/nihao/miniconda2/envs/py36/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/nihao/miniconda2/envs/py36/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/nihao/miniconda2/envs/py36/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/nihao/miniconda2/envs/py36/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/nihao/miniconda2/envs/py36/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by mattiasmar** [comment]
Hi,
Did you find any solution to this problem?
