### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by QL111111** [Tramac/awesome-semantic-segmentation-pytorch#19]
Hi, I follow installation steps to try to run this project.
There are some warnings during the setup phase, but no errors are reported.

But the following errors occur during the training phase：
```
(awesomeseg) root@ubuntu:/home/ql/pycharm/awesome-semantic-segmentation-pytorch/scripts# python train.py --model fcn32s --backbone vgg16 --dataset pascal_voc --lr 0.0001 --epochs 50
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from core.data.dataloader import get_segmentation_dataset
  File "/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/__init__.py", line 2, in <module>
    from .sync_bn.syncbn import *
  File "/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/sync_bn/syncbn.py", line 17, in <module>
    from .functions import *
  File "/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/sync_bn/functions.py", line 15, in <module>
    from core.nn.sync_bn import lib
  File "/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/sync_bn/lib/__init__.py", line 12, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 968, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/sync_bn/lib/cpu/sync_cpu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
(awesomeseg) root@ubuntu:/home/ql/pycharm/awesome-semantic-segmentation-pytorch/scripts#
```

----------------------
The warning for the setup phase is like this：
```
(awesomeseg) root@ubuntu:/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn# python setup.py build develop
running build
running build_ext
building '._C' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/home
creating build/temp.linux-x86_64-3.6/home/ql
creating build/temp.linux-x86_64-3.6/home/ql/pycharm
creating build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch
creating build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core
creating build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn
creating build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc
creating build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu
gcc -pthread -B /usr/local/anaconda3/envs/awesomeseg/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/anaconda3/envs/awesomeseg/include/python3.6m -c /home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /usr/local/anaconda3/envs/awesomeseg/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/anaconda3/envs/awesomeseg/include/python3.6m -c /home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/ca_cpu.cpp -o build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/ca_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /usr/local/anaconda3/envs/awesomeseg/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/anaconda3/envs/awesomeseg/include/python3.6m -c /home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/psa_cpu.cpp -o build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/psa_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /usr/local/anaconda3/envs/awesomeseg/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/anaconda3/envs/awesomeseg/include/python3.6m -c /home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/syncbn_cpu.cpp -o build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/syncbn_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /usr/local/anaconda3/envs/awesomeseg/compiler_compat -L/usr/local/anaconda3/envs/awesomeseg/lib -Wl,-rpath=/usr/local/anaconda3/envs/awesomeseg/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/vision.o build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/ca_cpu.o build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/psa_cpu.o build/temp.linux-x86_64-3.6/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn/csrc/cpu/syncbn_cpu.o -o build/lib.linux-x86_64-3.6/_C.cpython-36m-x86_64-linux-gnu.so
running develop
running egg_info
creating semantic_segmentation.egg-info
writing semantic_segmentation.egg-info/PKG-INFO
writing dependency_links to semantic_segmentation.egg-info/dependency_links.txt
writing top-level names to semantic_segmentation.egg-info/top_level.txt
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
reading manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
writing manifest file 'semantic_segmentation.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/_C.cpython-36m-x86_64-linux-gnu.so ->
Creating /usr/local/anaconda3/envs/awesomeseg/lib/python3.6/site-packages/semantic-segmentation.egg-link (link to .)
Adding semantic-segmentation 0.1 to easy-install.pth file

Installed /home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn
Processing dependencies for semantic-segmentation==0.1
Finished processing dependencies for semantic-segmentation==0.1
(awesomeseg) root@ubuntu:/home/ql/pycharm/awesome-semantic-segmentation-pytorch/core/nn# 

```
------------------------------
I don't know if setup's warning problem caused the error in the training phase.
How should I solve the mistakes in the training phase?
Thank you

**Comment by Tramac** [comment]
Hi, which is the version of PyTorch?

**Comment by QL111111** [comment]
python                    3.6.8                h0371630_0
pytorch                   1.0.1           cuda100py36he554f03_0

**Comment by Tramac** [comment]
I just tested the project in my server, there was no bug, so i have no idea how to fix it. Maybe because of the version of pytorch. You can try the following two choices:
1. Update pytorch to version 1.1.0, then remove [sync_bn](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/tree/master/core/nn/sync_bn), delete [`from .sync_bn.syncbn import *`](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/ca88a1942ec71f95a3d5dbb3e8d71000fc236380/core/nn/__init__.py#L2) and [`from core.nn import SyncBatchNorm`](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/ca88a1942ec71f95a3d5dbb3e8d71000fc236380/scripts/train.py#L25), change [this line](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/blob/ca88a1942ec71f95a3d5dbb3e8d71000fc236380/scripts/train.py#L161) to `BatchNorm2d = nn.SyncBatchNorm if args.distributed else nn.BatchNorm2d`.
2. remove [sync_bn](https://github.com/Tramac/awesome-semantic-segmentation-pytorch/tree/master/core/nn/sync_bn), change `from .sync_bn.syncbn import *` to `from .syncbn import *`.

**Comment by Tramac** [comment]
@QL111111 Does it work?

**Comment by QL111111** [comment]
Thank you very much. I upgraded pytorch to 1.1.0 and solved it.

**Comment by Tramac** [comment]
Great!
