### ISSUE TITLE
ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by ChaosZX** [Tramac/awesome-semantic-segmentation-pytorch#25]
When i try to run demo.py in windows 10 pytorch 1.1stable cuda10
C:\Users\123\Anaconda3\python.exe E:/awesome-semantic-segmentation-pytorch-master/awesome-semantic-segmentation-pytorch-master/scripts/demo.py
Traceback (most recent call last):
  File "E:/awesome-semantic-segmentation-pytorch-master/awesome-semantic-segmentation-pytorch-master/scripts/demo.py", line 12, in <module>
    from core.utils.visualize import get_color_pallete
  File "E:\awesome-semantic-segmentation-pytorch-master\awesome-semantic-segmentation-pytorch-master\core\__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "E:\awesome-semantic-segmentation-pytorch-master\awesome-semantic-segmentation-pytorch-master\core\nn\__init__.py", line 4, in <module>
    from .ca_block import *
  File "E:\awesome-semantic-segmentation-pytorch-master\awesome-semantic-segmentation-pytorch-master\core\nn\ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: cannot import name '_C'

Process finished with exit code 1

**Comment by Tramac** [comment]
Have you run `python setup.py build develop` successfully?

**Comment by ChaosZX** [comment]
thanks I just ran it and the problem solved

**Comment by Tramac** [comment]
Great!
