### ISSUE TITLE
run demo.py RuntimeError: invalid argument 6:

### ISSUE THREAD

**Issue by ChaosZX** [Tramac/awesome-semantic-segmentation-pytorch#29]
thanks  for your help I just finished training  and got the psanet model,then I just wanna run demo.py an error occurred ,can you help me to fix it again ,by the way os:win10 cuda10 pytorch1.1
C:\Users\123\Anaconda3\python.exe E:/awesome-semantic-segmentation-pytorch-master/awesome-semantic-segmentation-pytorch-master/scripts/demo.py
C:\Users\123/.torch/models\psanet_resnet50_pascal_voc.pth
Finished loading model!
Traceback (most recent call last):
  File "E:/awesome-semantic-segmentation-pytorch-master/awesome-semantic-segmentation-pytorch-master/scripts/demo.py", line 58, in <module>
    demo(args)
  File "E:/awesome-semantic-segmentation-pytorch-master/awesome-semantic-segmentation-pytorch-master/scripts/demo.py", line 49, in demo
    output = model(images)
  File "C:\Users\123\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\awesome-semantic-segmentation-pytorch-master\awesome-semantic-segmentation-pytorch-master\core\models\psanet.py", line 48, in forward
    x = self.head(c4)
  File "C:\Users\123\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\awesome-semantic-segmentation-pytorch-master\awesome-semantic-segmentation-pytorch-master\core\models\psanet.py", line 72, in forward
    global_feature = self.psa(x)
  File "C:\Users\123\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\awesome-semantic-segmentation-pytorch-master\awesome-semantic-segmentation-pytorch-master\core\models\psanet.py", line 88, in forward
    collect_fm = self.collect_attention(x)
  File "C:\Users\123\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\awesome-semantic-segmentation-pytorch-master\awesome-semantic-segmentation-pytorch-master\core\models\psanet.py", line 110, in forward
    fm = torch.bmm(reduce_x, torch.softmax(attention, dim=1))
RuntimeError: invalid argument 6: wrong matrix size at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMathBlas.cu:494

Process finished with exit code 1

**Comment by Tramac** [comment]
Please print the size of ```reduce_x``` and ```torch.softmax(attention, dim=1))```.

**Comment by ChaosZX** [comment]
attention= torch.Size([1, 3600, 3843])
reduce_x= torch.Size([1, 512, 3843])

**Comment by ChaosZX** [comment]
more detail 
![2118664421](https://user-images.githubusercontent.com/24428319/59409768-99dffb00-8de9-11e9-826c-f66cf398ef1b.jpg)

**Comment by Tramac** [comment]
Maybe due to the input size is not 480.

**Comment by ChaosZX** [comment]
> Maybe due to the input size is not 480.

So I need to resize the input size to 480*480?

**Comment by Tramac** [comment]
Yes，keep same with training input. Just for psanet and it is not necessary for other models.

**Comment by ChaosZX** [comment]
Ok thanks,I fix it and can you share me your training parameters such like batchsize and so on,I used gtx1060 to train the voc data ,the pixaccuracy is 65% and mIoU is 0.35,which can't reach as high as yours ,any advice?by the way i saw the hrnet model in you code when it will be available ?

**Comment by Tramac** [comment]
Parameters in README are ```lr=1e-4, batch_size=4, epochs=80```.
It's better to  reference to the parameters in the paper.
