### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HuaZheLei** [Tramac/awesome-semantic-segmentation-pytorch#34]
Thanks for your nice work. I can not figure out 'MixSoftmaxCrossEntropyLoss' in your code, which is the default loss function. Could you explain it for me?

**Comment by Tramac** [comment]
Hi，the default loss function is cross entropy loss，MixSoftmaxCrossEntropyLoss means auxiliary loss （deep supervised）+ cross entropy loss.

**Comment by HuaZheLei** [comment]
Thanks for your reply. When I use multi-gpu to evaluate my trained model, I get an error.
`Traceback (most recent call last):
  File "eval.py", line 108, in <module>
    evaluator = Evaluator(args)
  File "eval.py", line 49, in __init__
    self.model = self.model.module
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'FCN32s' object has no attribute 'module'`
My conmand is 
`export NGPUS=4
python -m torch.distributed.launch --nproc_per_node=$NGPUS eval.py --model fcn32s --backbone vgg16 --dataset coco_voc`

**Comment by roclark** [comment]
Hey @HuaZheLei, I'm running into this issue as well (for ENet specifically, but the same principle applies). Did you find a resolution?

**Comment by roclark** [comment]
Hello again @HuaZheLei, not sure if you are still looking at this or not, but I just created a pull request (#50) which now fully supports multi-GPU evaluation. I tested with the following command:
```
export NGPUS=8
python -m torch.distributed.launch --nproc_per_node=$NGPUS eval.py --model enet --dataset citys
```
Feel free to give it a shot and let me know if it solves your issue!
