### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by 1535315854** [Tramac/Awesome-semantic-segmentation-pytorch#4]
@Tramac 

Hello, Thank you for your wonderful work! 

I run your code in Windows and I encounter this error:

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from models.model_zoo import get_segmentation_model
  File "D:\PyTorch\Awesome-semantic-segmentation-pytorch-master\models\__init__.py", line 2, in <module>
    from .model_zoo import get_model, get_model_list
  File "D:\PyTorch\Awesome-semantic-segmentation-pytorch-master\models\model_zoo.py", line 2, in <module>
    from .fcn import *
  File "D:\PyTorch\Awesome-semantic-segmentation-pytorch-master\models\fcn.py", line 7, in <module>
    from models.utils import weights_init
ModuleNotFoundError: No module named 'models.utils'

Could you please help me? Thanks a lot!

**Comment by Tramac** [comment]
Hi, you can delete codes `from models.utils import weights_init`, and function `_initialize_weights()` in 'fcn.py', These codes are not used in the new version.
I am very sorry for my negligence， i will fix these bug later, Thank you for pointing out！
