### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by 1535315854** [Tramac/Awesome-semantic-segmentation-pytorch#5]
@Tramac 
Thank you for your help!

I try to train pspnet with auxiliary loss as in the paper, the args are as follows:

Namespace(aux=True, aux_weight=0.4, backbone='resnet50', base_size=520, batch_size=2, crop_size=480, dataset='pascal_voc', device=device(type='cuda', index=0), epochs=10, eval=False, lr=0.01, model='psp', momentum=0.9, no_val=True, resume=None, save_folder='./ckptmodels', start_epoch=0, train_split='train', weight_decay=0.0001)

And I get this error:

Traceback (most recent call last):
  File "train.py", line 210, in <module>
    trainer = Trainer(args)
  File "train.py", line 118, in __init__
    aux=args.aux, crop_size=args.crop_size)
  File "D:\PyTorch\Awesome-semantic-segmentation-pytorch-master\models\model_zoo.py", line 63, in get_segmentation_model
    return models[model](**kwargs)
  File "D:\PyTorch\Awesome-semantic-segmentation-pytorch-master\models\pspnet.py", line 138, in get_psp
    model = PSPNet(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
  File "D:\PyTorch\Awesome-semantic-segmentation-pytorch-master\models\pspnet.py", line 41, in __init__
    self.auxlayer = _FCNHead(1024, nclass, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'norm_layer'

Could you please help me? Thank you very much!

**Comment by Tramac** [comment]
Hi, please add code `def __init__(self, in_channels, channels, norm_layer=nn.BatchNorm2d, **kwargs)` in `_FCNHead(nn.Module)`, which in `fcn.py`.
I'm sorry for my careless.

**Comment by 1535315854** [comment]
Thank you very much for your help!
