### ISSUE TITLE
How to get the xception base model file ？

### ISSUE THREAD

**Issue by tomjerrygithub** [Tramac/awesome-semantic-segmentation-pytorch#82]
deeplabv3+  without  xception base file ， very slow 
can you share the base model file ? 
or how to get it?
thx

**Comment by sainatarajan** [comment]
I have tried 2-3 different xception.pth files available all over the internet and it always throws some dictionary error. This is obvious since the model was built by different people and hence not compatible with the model built by this repo owner.

**Comment by MohiFaruq** [comment]
I am facing the same issue. @Tramac Please provide us with the specific xception base model. Or else runnug deeplabv3_plus is not convenient. Thanks :)

**Comment by lr1234567** [comment]
你好，我也遇到了这个问题，请问您是怎么解决的？下面是报错日志
Traceback (most recent call last):
  File "train.py", line 340, in <module>
    trainer = Trainer(args)
  File "train.py", line 167, in __init__
    aux=args.aux,  norm_layer=BatchNorm2d).to(self.device)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/model_zoo.py", line 137, in get_segmentation_model
    return models[model](**kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 131, in get_deeplabv3_plus
    model = DeepLabV3Plus(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 39, in __init__
    self.pretrained = get_xception(pretrained=pretrained_base, output_stride=output_stride, **kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/base_models/xception.py", line 390, in get_xception
    model.load_state_dict(torch.load(get_model_file('xception', root=root)))
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/model_store.py", line 68, in get_model_file
    raise ValueError('Model file is not found. Downloading or trainning.')
ValueError: Model file is not found. Downloading or trainning.

**Comment by sainatarajan** [comment]
@lr1234567 `xception` model is not available.

**Comment by lr1234567** [comment]
> @lr1234567 `xception` backbone is not available. So try a different model such as PSPNet.
好的 感谢告知

**Comment by bbbts** [comment]
> I have tried 2-3 different xception.pth files available all over the internet and it always throws some dictionary error. This is obvious since the model was built by different people and hence not compatible with the model built by this repo owner.

@tomjerrygithub @sainatarajan @pyradd I am having the same issue training on deeplabv3_plus with xception. Were you able to solve it? Were you able to find the base xception backbone? Kindly help
