### ISSUE TITLE
When I run the download script, the follow problem occurred.(python ade20k.py --download-dir ../datasets/ade)

### ISSUE THREAD

**Issue by BunnySF** [Tramac/awesome-semantic-segmentation-pytorch#87]
Traceback (most recent call last):
  File "D:/CodeViewing/awesome-semantic-segmentation-pytorch-master/core/data/downloader/ade20k.py", line 12, in <module>
    from core.utils import download, makedirs
  File "D:\CodeViewing\awesome-semantic-segmentation-pytorch-master\core\__init__.py", line 1, in <module>
    from . import nn, models, utils, data
  File "D:\CodeViewing\awesome-semantic-segmentation-pytorch-master\core\nn\__init__.py", line 4, in <module>
    from .ca_block import *
  File "D:\CodeViewing\awesome-semantic-segmentation-pytorch-master\core\nn\ca_block.py", line 6, in <module>
    from core.nn import _C
ImportError: cannot import name '_C'

**Comment by sainatarajan** [comment]
Have you followed these steps properly?
```
# the following will install the lib with symbolic links, so that you can modify
# the files if you want and won't need to re-build it
cd awesome-semantic-segmentation-pytorch/core/nn
python setup.py build develop
```
