### ISSUE TITLE
求助求助求助

### ISSUE THREAD

**Issue by lr1234567** [Tramac/awesome-semantic-segmentation-pytorch#98]
Traceback (most recent call last):
  File "train.py", line 340, in <module>
    trainer = Trainer(args)
  File "train.py", line 167, in __init__
    aux=args.aux,  norm_layer=BatchNorm2d).to(self.device)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/model_zoo.py", line 137, in get_segmentation_model
    return models[model](**kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 131, in get_deeplabv3_plus
    model = DeepLabV3Plus(datasets[dataset].NUM_CLASS, backbone=backbone, pretrained_base=pretrained_base, **kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/deeplabv3_plus.py", line 39, in __init__
    self.pretrained = get_xception(pretrained=pretrained_base, output_stride=output_stride, **kwargs)
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/base_models/xception.py", line 390, in get_xception
    model.load_state_dict(torch.load(get_model_file('xception', root=root)))
  File "/home/lr/桌面/awesome-semantic-segmentation-pytorch-master.2/core/models/model_store.py", line 68, in get_model_file
    raise ValueError('Model file is not found. Downloading or trainning.')
ValueError: Model file is not found. Downloading or trainning.

deeplab v3 plus 用的基本模型xception，在哪找root路径？

**Comment by wuwenbin970731** [comment]
在deeplabv3_plus.py中修改get_deeplabv3_plus函数的默认参数pretrained_base为false即可

**Comment by zjuxwg0401** [comment]
我也遇到了相似的问题，请问楼主解决了吗？

**Comment by Wongshy** [comment]
楼主问题解决了吗
